export const breakablePassives = 
{
	"Abaddon": ["abaddon_borrowed_time", "abaddon_frostmourne"],
	"Alchemist": ["alchemist_goblins_greed"],
	"Ancient Apparition": [],
	"Anti-Mage": ["antimage_mana_break", "antimage_counterspell"],
	"Arc Warden": [],
	"Axe": ["axe_counter_helix"],
	"Bane": ["bane_enfeeble"],
	"Batrider": [],
	"Beastmaster": ["beastmaster_inner_beast"],
	"Bloodseeker": ["bloodseeker_thirst"],
	"Bounty Hunter": ["bounty_hunter_jinada"],
	"Brewmaster": [],
	"Bristleback": ["bristleback_bristleback", "bristleback_warpath"],
	"Broodmother": ["broodmother_incapacitating_bite"],
	"Centaur Warrunner": ["centaur_return"],
	"Chaos Knight": ["chaos_knight_chaos_strike"],
	"Chen": ["chen_divine_favor"],
	"Clinkz": [],
	"Clockwerk": [],
	"Crystal Maiden": [],
	"Dark Seer": [],
	"Dark Willow": [],
	"Dawnbreaker": ["dawnbreaker_luminosity"],
	"Dazzle": ["dazzle_bad_juju"],
	"Death Prophet": [],
	"Disruptor": [],
	"Doom": [],
	"Dragon Knight": ["dragon_knight_dragon_blood"],
	"Drow Ranger": ["drow_ranger_marksmanship"],
	"Earth Spirit": [],
	"Earthshaker": ["earthshaker_aftershock"],
	"Elder Titan": ["elder_titan_natural_order"],
	"Ember Spirit": [],
	"Enchantress": ["enchantress_untouchable"],
	"Enigma": [],
	"Faceless Void": ["faceless_void_time_lock"],
	"Grimstroke": [],
	"Gyrocopter": ["gyrocopter_side_gunner"],
	"Hoodwink": ["hoodwink_scurry"],
	"Huskar": ["huskar_berserkers_blood"],
	"Invoker": [],
	"Jakiro": [],
	"Io": [],
	"Juggernaut": ["juggernaut_blade_dance"],
	"Keeper of the Light": [],
	"Kunkka": [],
	"Legion Commander": ["legion_commander_moment_of_courage"],
	"Leshrac": [],
	"Lich": [],
	"Lifestealer": ["life_stealer_feast"],
	"Lina": ["lina_fiery_soul"],
	"Lion": [],
	"Lone Druid": ["lone_druid_spirit_link"],
	"Luna": ["luna_lunar_blessing", "luna_moon_glaive"],
	"Lycan": ["lycan_feral_impulse"],
	"Magnus": [],
	"Marci": [],
	"Mars": ["mars_bulwark"],
	"Medusa": [],
	"Meepo": ["meepo_ransack"],
	"Mirana": ["mirana_starfall"],
	"Monkey King": ["monkey_king_jingu_mastery"],
	"Morphling": [],
	"Naga Siren": ["naga_siren_rip_tide"],
	"Nature's Prophet": [],
	"Necrophos": ["necrolyte_heartstopper_aura"],
	"Night Stalker": ["night_stalker_hunter_in_the_night"],
	"Nyx Assassin": [],
	"Ogre Magi": ["ogre_magi_multicast"],
	"Omniknight": ["omniknight_degen_aura"],
	"Oracle": [],
	"Outworld Destroyer": ["obsidian_destroyer_equilibrium"],
	"Pangolier": ["pangolier_lucky_shot"],
	"Phantom Assassin": ["phantom_assassin_blur", "phantom_assassin_coup_de_grace"],
	"Phantom Lancer": ["phantom_lancer_phantom_edge", "phantom_lancer_juxtapose"],
	"Phoenix": [],
	"Puck": [],
	"Pudge": [],
	"Pugna": [],
	"Queen of Pain": [],
	"Razor": ["razor_unstable_current"],
	"Riki": ["riki_backstab"],
	"Rubick": ["rubick_arcane_supremacy"],
	"Sand King": ["sandking_caustic_finale"],
	"Shadow Demon": [],
	"Shadow Fiend": ["nevermore_necromastery", "nevermore_dark_lord"],
	"Shadow Shaman": [],
	"Silencer": [],
	"Skywrath Mage": [],
	"Slardar": ["slardar_bash"],
	"Slark": ["slark_essence_shift", "slark_shadow_dance"],
	"Snapfire": [],
	"Sniper": ["sniper_headshot", "sniper_take_aim"],
	"Spectre": ["spectre_desolate", "spectre_dispersion"],
	"Spirit Breaker": ["spirit_breaker_greater_bash"],
	"Storm Spirit": ["storm_spirit_overload"],
	"Sven": ["sven_great_cleave"],
	"Techies": [],
	"Templar Assassin": ["templar_assassin_psi_blades"],
	"Terrorblade": [],
	"Tidehunter": ["tidehunter_kraken_shell"],
	"Timbersaw": ["shredder_reactive_armor"],
	"Tinker": [],
	"Tiny": [],
	"Treant Protector": [],
	"Troll Warlord": ["troll_warlord_berserkers_rage", "troll_warlord_fervor"],
	"Tusk": [],
	"Underlord": ["abyssal_underlord_atrophy_aura"],
	"Undying": [],
	"Ursa": ["ursa_fury_swipes"],
	"Vengeful Spirit": ["vengefulspirit_command_aura"],
	"Venomancer": ["venomancer_poison_sting"],
	"Viper": ["viper_corrosive_skin"],
	"Visage": ["visage_gravekeepers_cloak"],
	"Void Spirit": [],
	"Warlock": [],
	"Weaver": ["weaver_geminate_attack"],
	"Windranger": [],
	"Winter Wyvern": [],
	"Witch Doctor": [],
	"Wraith King": ["skeleton_king_mortal_strike", "skeleton_king_vampiric_aura"],
	"Zeus": ["zuus_static_field"]
}