export const damageType = 
{
    "Abaddon": "magical",
    "Alchemist": "physical",
    "Ancient Apparition": "magical",
    "Anti-Mage": "physical",
    "Arc Warden": "neutral",
    "Axe": "pure",
    "Bane": "pure",
    "Batrider": "magical",
    "Beastmaster": "neutral",
    "Bloodseeker": "neutral",
    "Bounty Hunter": "neutral",
    "Brewmaster": "neutral",
    "Bristleback": "physical",
    "Broodmother": "physical",
    "Centaur Warrunner": "magical",
    "Chaos Knight": "physical",
    "Chen": "physical",
    "Clinkz": "physical",
    "Clockwerk": "magical",
    "Crystal Maiden": "magical",
    "Dark Seer": "magical",
    "Dark Willow": "magical",
    "Dawnbreaker": "neutral",
    "Dazzle": "physical",
    "Death Prophet": "neutral",
    "Disruptor": "magical",
    "Doom": "magical",
    "Dragon Knight": "physical",
    "Drow Ranger": "physical",
    "Earth Spirit": "magical",
    "Earthshaker": "magical",
    "Elder Titan": "neutral",
    "Ember Spirit": "neutral",
    "Enchantress": "pure",
    "Enigma": "magical",
    "Faceless Void": "physical",
    "Grimstroke": "magical",
    "Gyrocopter": "neutral",
    "Hoodwink": "neutral",
    "Huskar": "neutral",
    "Invoker": "neutral",
    "Io": "magical",
    "Jakiro": "magical",
    "Juggernaut": "physical",
    "Keeper of the Light": "magical",
    "Kunkka": "physical",
    "Legion Commander": "physical",
    "Leshrac": "magical",
    "Lich": "magical",
    "Lifestealer": "physical",
    "Lina": "magical",
    "Lion": "magical",
    "Lone Druid": "physical",
    "Luna": "neutral",
    "Lycan": "physical",
    "Magnus": "physical",
    "Marci": "neutral",
    "Mars": "neutral",
    "Medusa": "physical",
    "Meepo": "physical",
    "Mirana": "magical",
    "Monkey King": "physical",
    "Morphling": "neutral",
    "Naga Siren": "physical",
    "Nature's Prophet": "physical",
    "Necrophos": "magical",
    "Night Stalker": "physical",
    "Nyx Assassin": "magical",
    "Ogre Magi": "magical",
    "Omniknight": "pure",
    "Oracle": "magical",
    "Outworld Devourer": "neutral",
    "Outworld Destroyer": "neutral",
    "Pangolier": "neutral",
    "Phantom Assassin": "physical",
    "Phantom Lancer": "physical",
    "Phoenix": "magical",
    "Puck": "magical",
    "Pudge": "magical",
    "Pugna": "magical",
    "Queen of Pain": "neutral",
    "Razor": "physical",
    "Riki": "physical",
    "Rubick": "magical",
    "Sand King": "magical",
    "Shadow Demon": "neutral",
    "Shadow Fiend": "magical",
    "Shadow Shaman": "neutral",
    "Silencer": "neutral",
    "Skywrath Mage": "magical",
    "Slardar": "physical",
    "Slark": "physical",
    "Snapfire": "magical",
    "Sniper": "physical",
    "Spectre": "physical",
    "Spirit Breaker": "magical",
    "Storm Spirit": "magical",
    "Sven": "physical",
    "Techies": "magical",
    "Templar Assassin": "physical",
    "Terrorblade": "physical",
    "Tidehunter": "neutral",
    "Timbersaw": "pure",
    "Tinker": "magical",
    "Tiny": "neutral",
    "Treant Protector": "magical",
    "Troll Warlord": "physical",
    "Tusk": "physical",
    "Underlord": "magical",
    "Undying": "neutral",
    "Ursa": "physical",
    "Vengeful Spirit": "neutral",
    "Venomancer": "magical",
    "Viper": "magical",
    "Visage": "neutral",
    "Void Spirit": "magical",
    "Warlock": "magical",
    "Weaver": "physical",
    "Windranger": "physical",
    "Winter Wyvern": "magical",
    "Witch Doctor": "neutral",
    "Wraith King": "physical",
    "Zeus": "magical"
}