/**
 * dispellableBuffs.ts contains all information about dispellable buffs from hero kills in the game.
 *
 * IMPORTANT: Use the following function to access dispellable buffs: Dota2.hero_abilities.getDispellableBuffs()
 *
 * Unfortunately file can't be replaced with static data from Dota 2 (24.2.2022)
 *
 * Copyright (C) Dota Coach, 2023. All rights reserved.
 */

export const dispellableBuffs: Record<string, string[]> = {
  Abaddon: ["abaddon_aphotic_shield", "abaddon_frostmourne"],
  Alchemist: ["alchemist_corrosive_weaponry", "alchemist_chemical_rage"],
  "Ancient Apparition": [],
  "Anti-Mage": [],
  "Arc Warden": [],
  Axe: ["axe_culling_blade"],
  Bane: [],
  Batrider: [],
  Beastmaster: [],
  Bloodseeker: ["bloodseeker_bloodrage"],
  "Bounty Hunter": [],
  Brewmaster: ["brewmaster_cinder_brew"],
  Bristleback: [],
  Broodmother: [],
  "Centaur Warrunner": ["centaur_double_edge"],
  "Chaos Knight": [],
  Chen: ["chen_divine_favor"],
  Clinkz: [],
  Clockwerk: [`rattletrap_jetpack`],
  "Crystal Maiden": [],
  "Dark Seer": ["dark_seer_ion_shell", "dark_seer_surge"],
  "Dark Willow": [],
  Dawnbreaker: ["dawnbreaker_luminosity"],
  Dazzle: [],
  "Death Prophet": [],
  Disruptor: [],
  Doom: [],
  "Dragon Knight": [],
  "Drow Ranger": [],
  "Earth Spirit": [],
  Earthshaker: ["earthshaker_enchant_totem"],
  "Elder Titan": ["elder_titan_ancestral_spirit"],
  "Ember Spirit": ["ember_spirit_flame_guard"],
  Enchantress: [],
  Enigma: [],
  "Faceless Void": ["faceless_void_time_dilation"],
  Grimstroke: ["grimstroke_spirit_walk"],
  Gyrocopter: ["gyrocopter_rocket_barrage"],
  Hoodwink: ["hoodwink_scurry"],
  Huskar: [],
  Invoker: ["invoker_alacrity"],
  Jakiro: [],
  Io: [],
  Juggernaut: [],
  "Keeper of the Light": ["keeper_of_the_light_chakra_magic"],
  Kunkka: [],
  "Legion Commander": [
    "legion_commander_overwhelming_odds",
    "legion_commander_press_the_attack",
  ],
  Leshrac: [],
  Lich: ["lich_frost_shield"],
  Lifestealer: [],
  Lina: [],
  Lion: [],
  "Lone Druid": [
    /* "lone_druid_true_form_battle_cry" no longer available */
	`lone_druid_savage_roar` /* Only the buff with Aghanim Shard on hero */ ,
  ],
  Luna: [],
  Lycan: ["lycan_howl"],
  Magnus: ["magnataur_empower"],
  Marci: [
    `marci_companion_run` /* rebound */ /* "marci_guardian" */ /* Sidekick */,
  ],
  Mars: [],
  Medusa: [],
  Meepo: [],
  Mirana: ["mirana_leap"],
  "Monkey King": ["monkey_king_jingu_mastery", "monkey_king_mischief"],
  Morphling: [],
  Muerta: [],
  "Naga Siren": [],
  "Nature's Prophet": [`furion_teleportation`],
  Necrophos: ["necrolyte_sadist"],
  "Night Stalker": [],
  "Nyx Assassin": [],
  "Ogre Magi": [`ogre_magi_bloodlust`, `ogre_magi_smash`],
  Omniknight: [`omniknight_guardian_angel`],
  Oracle: ["oracle_fates_edict", "oracle_purifying_flames"],
  "Outworld Destroyer": [],
  "Primal Beast": [
    "primal_beast_onslaught",
    `primal_beast_uproar`,
  ],
  Pangolier: ["pangolier_shield_crash"],
  "Phantom Assassin": ["phantom_assassin_phantom_strike"],
  "Phantom Lancer": ["phantom_lancer_phantom_edge"],
  Phoenix: [],
  Puck: [],
  Pudge: [],
  Pugna: ["pugna_decrepify"],
  "Queen of Pain": [],
  Razor: [],
  Riki: [],
  Rubick: [],
  "Sand King": [],
  "Shadow Demon": [`shadow_demon_disseminate`],
  "Shadow Fiend": [],
  "Shadow Shaman": [],
  Silencer: [],
  "Skywrath Mage": [],
  Slardar: ["slardar_sprint"],
  Slark: [],
  Snapfire: [],
  Sniper: ["sniper_take_aim"],
  Spectre: [],
  "Spirit Breaker": ["spirit_breaker_bulldoze"],
  "Storm Spirit": ["storm_spirit_overload"],
  Sven: ["sven_warcry"],
  Techies: ["techies_reactive_tazer"],
  "Templar Assassin": [],
  Terrorblade: [],
  Tidehunter: [],
  Timbersaw: [
    "shredder_whirling_death",
    "shredder_reactive_armor" /* Only the active barrier from Aghanims Scepter */,
  ],
  Tinker: [`tinker_defense_matrix`],
  Tiny: [],
  "Treant Protector": ["treant_living_armor"],
  "Troll Warlord": [],
  Tusk: [],
  Underlord: [],
  Undying: [],
  Ursa: ["ursa_overpower"],
  "Vengeful Spirit": ["vengefulspirit_nether_swap"],
  Venomancer: [],
  Viper: [],
  Visage: ["visage_grave_chill"],
  "Void Spirit": ["void_spirit_resonant_pulse"],
  Warlock: ["warlock_shadow_word"],
  Weaver: [],
  Windranger: ["windrunner_windrun"],
  "Winter Wyvern": [],
  "Witch Doctor": [],
  "Wraith King": [],
  Zeus: [],
};
