/**
 *
 * Source: Dota2.com
 *
 * Copyright Dota Coach, 2022
 */

export const heroSummary = {
  Abaddon: "Shields his allies or himself from attacks",
  Alchemist: "Earns extra gold from unit kills and bounty runes",
  "Ancient Apparition":
    "Launches a powerful icy blast from anywhere on the map",
  "Anti-Mage": "Slashes his foes with mana-draining attacks",
  "Arc Warden": "Creates a copy of himself to split push",
  Axe: "Taunts and forces enemies to attack him",
  Bane: "Puts his enemies to sleep, incapacitating them",
  Batrider: "Can lasso an enemy away from his team",
  Beastmaster: "Summons beasts to aid his hunt",
  Bloodseeker: "Chases down low health enemies with increased speed",
  "Bounty Hunter": "Loots and collects bounties off of his enemies",
  Brewmaster: "Splits into three elemental spirits with unique abilities",
  Bristleback: "Takes reduced damage when facing away from enemies",
  Broodmother: "Hunts with her army of spiderlings",
  "Centaur Warrunner": "Reflects damage back to his attackers",
  "Chaos Knight": "Has strong but random damage output",
  Chen: "Converts creeps to his cause, building an army",
  Clinkz: "Stalks invisibly to ambush lone enemies",
  Clockwerk: "Launches himself into enemies with his hookshot",
  "Crystal Maiden": "Unleashes a high damage blizzard upon her foes",
  "Dark Seer": "Pulls and manipulates his enemies' positions",
  "Dark Willow": "Has an arsenal of disables at her disposal",
  Dawnbreaker: "Leaps to aid her allies, wherever they are on the map",
  Dazzle: "Powerful healer who can briefly prevent death",
  "Death Prophet": "Summons an army of ghosts to attack",
  Disruptor: "Traps and silences foes in his static storm",
  Doom: "Can prevent a single enemy from using abilties and items",
  "Dragon Knight": "Transforms into a formidable ranged dragon",
  "Drow Ranger": "Slows with her frost-tipped arrows",
  "Earth Spirit": "Disables and repositions his enemies",
  Earthshaker: "Disrupts enemy team with his chain stuns",
  "Elder Titan": "Damages and disables with his astral spirit",
  "Ember Spirit": "Apidly strikes and chains his foes",
  Enchantress: "Enchants neutral creeps to do her bidding",
  Enigma: "Traps and damages enemies in a black hole",
  "Faceless Void": "Can freeze his enemies in time",
  Grimstroke: "Disables enemies with a swipe of his brush",
  Gyrocopter: "Barrages with his cannon and homing missiles",
  Hoodwink: "Shackles her enemies to trees",
  Huskar: "Sacrifices his health to deal more damage",
  Invoker: "Weaves magic with an array of spell combos",
  Io: "Links to its allies to buff them",
  Jakiro: "Freezes and burns enemies with magic",
  Juggernaut: "Slices through his enemies with precise strikes",
  "Keeper of the Light": "Provides instant mana to allies",
  Kunkka: "Disrupts enemy positioning and disables them",
  "Legion Commander": "Increases power with each duel victory",
  Leshrac: "Can deal heavy damage in an aura around himself",
  Lich: "Unleashes a powerful attack that bounces between enemies",
  Lifestealer: "Infests other units for mobility and strength",
  Lina: "Increases attack and speed with every spell",
  Lion: "Steals enemy mana to fuel his own abilities",
  "Lone Druid": "Steals enemy mana to fuel his own abilities",
  Luna: "Tears into her enemies with bouncing attacks",
  Lycan: "Shapeshifts into a ferocious beast",
  Magnus: "Charges in to reposition his enemies",
  Marci: "Dashes around pummeling enemies with rapid attacks",
  Mars: "Traps his foes in an inescapable arena",
  Medusa: "Immobilizes her enemies with her stone gaze",
  Meepo: "Five are stronger than one",
  Mirana: "Stuns enemies with precise arrows from afar",
  "Monkey King": "Springs from the cover of the tree tops",
  Morphling: "Rides the waves to flank enemies",
  "Naga Siren": "Able to capitivate and disable enemies with her song",
  "Nature's Prophet": "Able to teleport to any location on the map at will",
  Necrophos: "Damages enemies and heals allies simultaneously",
  "Night Stalker": "Enpowered by the shadows of nightfall",
  "Nyx Assassin": "Reflects enemy damage and stuns",
  "Ogre Magi": "Uses a touch of luck to amplify his skills",
  Omniknight: "Tanky frontliner who protects and heals his allies",
  Oracle: "Alters the fates of heroes with his buffs and nukes",
  "Outworld Devourer": "Can imprison a hero, making them invulnerable",
  "Outworld Destroyer": "Can imprison a hero, making them invulnerable",
  Pangolier: "Dashes and rolls in to disrupt enemy movements",
  "Phantom Assassin": "Blinks onto her foes with critical strikes",
  "Phantom Lancer": "Creates illusions of himself to trick or attack foes",
  Phoenix: "Heals and damages at the sacrifice of its own health",
  Puck: "Orbs to enemies and silences them",
  Pudge: "Hooks and pulls enemies towards him",
  Pugna: "Drains enemy life to heal himself",
  "Queen of Pain": "Blinks in to deal massive magical damage",
  Razor: "Steals enemy damage to add to his own",
  Riki: "Remains permanently invisible until the moment to strike",
  Rubick: "Steals the spells of his enemies to use against them",
  "Sand King": "Burrows to stun and slow enemies",
  "Shadow Demon": "Stacks exponential poison damage against his foes",
  "Shadow Fiend": "Unleashes the souls of fallen enemies for damage",
  "Shadow Shaman": "Summons powerful serpent wards to deal damage",
  Silencer: "Can silence all enemies on the map",
  "Skywrath Mage": "Casts high damage magical spells on a single target",
  Slardar: "Chases down his enemies to weaken and bash them",
  Slark: "Slips in and out of skirmishes",
  Snapfire: "Mows down her enemies with heavy artillery and trusty lizard",
  Sniper: "Picks off his enemies from afar",
  Spectre: "Haunts her enemies and teleports to her target",
  "Spirit Breaker": "Charges down enemies from anywhere on the map",
  "Storm Spirit": "Zips across the map to engage in fights",
  Sven: "Cleaves down enemies with his incredible strength",
  Techies: "Surprises enemies with invisible landmines and traps",
  "Templar Assassin": "Slows down enemies with traps",
  Terrorblade: "Transforms into a powerful ranged demon",
  Tidehunter: "Durable hero who shrugs off enemy damage",
  Timbersaw: "Chops through the forest to face his foes",
  Tinker: "Demolishes his enemies with swarms of machines",
  Tiny: "Grows in size and strength as battle ensues",
  "Treant Protector": "Calls upon the forest to root his foes",
  "Troll Warlord": "Swaps between ranged and melee attacks at will",
  Tusk: "Snowballs into his enemies to stun",
  Underlord: "Teleports his team in and out of battle",
  Undying: "Summons hordes of zombies to attack his foes",
  Ursa: "Deals more damage with every hit to the same foe",
  "Vengeful Spirit": "Can swap herself with any nearby hero",
  Venomancer: "Deals damage over time with venomous attacks",
  Viper: "Poisonous toxins chip away armor and slow enemies",
  Visage: "Scouts and attacks with his familiars",
  "Void Spirit": "Steps in and out of the mortal plane to strike his foes",
  Warlock: "Summons powerful demons to fight at his side",
  Weaver: "Rewinds time to reverse damage and position",
  Windranger: "Fires swift flurry of arrows at a single target",
  "Winter Wyvern": "Able to force her enemies to attack their own ally",
  "Witch Doctor": "Channels a high damage death ward",
  "Wraith King": "Can reincarnate instantly upon death",
  Zeus: "Strikes enemies near and far with lightning",
};
